name: Build Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout Repo
    - uses: actions/checkout@v3

    - uses: docker/build-push-action@v2
      with:
        tags: hardhat:latest
        push: false

    - uses: addnab/docker-run-action@v3
      with:
        image: hardhat:latest
        
        run: echo "hello world"

    # - name: Compile
    #   run: |
    #     npx hardhat compile
    
    # - name: Test
    #   run: |
    #     npx hardhat test
    
    # - name: Run
    #   run: |
    #     npx hardhat run deployments/deployToken.js
